# This file sets up testing in each Python version that package supports.
# See the documentation for each plugin for more details on how it works and how to configure it.
# * Pipeline environment variables are automatically available within the test steps.
# * The test plugin will generate a wait step before running the SonarQube plugin. If you want
#   to add a step that runs at the same time as the test steps, put it BEFORE the python-test plugin.

- label: ":pipeline: :pytest: Generate package check steps"
  plugins:
    - ssh://git@github.csnzoo.com/shared/python-package-buildkite-plugin.git#v2.1.0:
        python-version:
          - "python38"
          - "python37"
          - "python36"
        os-version: "centos75"
        package-import-name: "pydantic"

- label: ":pipeline: :pytest: Generate test steps"
  plugins:
    - ssh://git@github.csnzoo.com/shared/python-test-buildkite-plugin.git#v2.2.0:
        python-version:
          - "python38"
          - "python37"
          - "python36"
        os-version: "centos75"
        sonarqube-project-key: "mep-pydantic"
        source-dir: "pydantic"
